### ISSUE TITLE
Fix upstream sync issues on windows

### ISSUE THREAD

**Issue by LukasGentele** [covexo/devspace#374] opened 2018-11-08 21:12 UTC
**What happened?**  
Running `devspace up` starts the initial sync process. If many files are synced down and changed locally, it may happen that the file watcher process on windows dies without any errors which leads to a non-functional upstream sync.

**What did you expect to happen instead?**  
File watcher should not die when changing many files locally or they should be restarted automatically to ensure that upstream file syncing always works.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
1. Checkout a nodejs project with a large number of dependencies on windows 
2. run `devspace up`
3. change a file locally and check if it has been synchronized to the remote container

**Local Environment:**  
- Operating System: windows
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: DevSpace Cloud Enterprise

**Anything else we need to know?**  
This might also affect the quickstart guide making it even more important.

/kind bug

**Comment by FabianKramm** [comment] 2018-11-09 16:37
I tracked down the issue to the github.com/rjeczalik/notify library. The problem is that the windows API syscall `syscall.GetQueuedCompletionStatus` does not write any bytes into the overlapped struct (not sure why though), which leads to the skip of the syscall `syscall.ReadDirectoryChanges`, which in return leads to an endless waiting in the next loop run of `syscall.GetQueuedCompletionStatus`. I'll implement a potential fix and test some more and then open a pull request to fix that issue in the library.

**Comment by FabianKramm** [comment] 2018-11-27 10:01
I created a pull request in the library that was merged yesterday which should fix the issue, so we only have to update our dependencies.

**Closed** 2018-11-27 10:32 UTC
Labels: area/sync, priority/critical, system/windows
